### ISSUE TITLE
tutorial: Contributing additional plugins

### ISSUE THREAD

**Issue by sparsonslab** [force-h2020/force-docs#11]
## Description
Thoughts, plans and issues related to the 'Contributing additional plugins' section of the tutorial workshop: a 2-4 hour tutorial for the BDSS.

## Related Issues
One of the topics in #4, design of tutorial workshop.

**Comment by flongford** [comment]
This can be adapted from the BDSS documentation, it is a guide for contributing additional python packages as Envisage plugins

**Comment by flongford** [comment]
I am currently wearing the beard of shame for accidentally committing both https://github.com/force-h2020/force-docs/commit/b83eee3107efc1fd5ab9bb7271c38e1c0049541f and https://github.com/force-h2020/force-docs/commit/7d0e62ca4925925cc9cfa977a7b7434e5c97219f to `master`

**Comment by sparsonslab** [comment]
I didn't know a beard came with shame, but don't worry about it!
