### ISSUE TITLE
tutorial: What is the BDSS?

### ISSUE THREAD

**Issue by sparsonslab** [force-h2020/force-docs#6]
## Description
Thoughts, plans and issues related to the 'What is the BDSS?' section of the tutorial workshop:
a 2-4 hour tutorial for the BDSS.

## Related Issues
One of the topics in #4, design of tutorial workshop.

**Comment by flongford** [comment]
We can include a high-level conceptual description of the BDSS components here (`DataSource`, `Workflow`, `MCO`, `KPIs`)

**Comment by flongford** [comment]
Also could include 'What real life use cases could be investigated using the BDSS?'

**Comment by flongford** [comment]
@sparsonslab - has this been taken care of by #14?
