### ISSUE TITLE
tutorial: Installation of core packages

### ISSUE THREAD

**Issue by sparsonslab** [force-h2020/force-docs#7]
## Description
Thoughts, plans and issues related to the 'Installation of core packages' section of the tutorial workshop: a 2-4 hour tutorial for the BDSS.

## Related Issues
One of the topics in #4, design of tutorial workshop.

**Comment by flongford** [comment]
Note: this has been partially taken care of by #2, but we should re-visit the `installation.rst` document to include any additional plugins needed by the tutorial.
